//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab6.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCiudades", ReplyAction="http://tempuri.org/IService1/getCiudadesResponse")]
        string[] getCiudades();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCiudades", ReplyAction="http://tempuri.org/IService1/getCiudadesResponse")]
        System.Threading.Tasks.Task<string[]> getCiudadesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Informacion", ReplyAction="http://tempuri.org/IService1/InformacionResponse")]
        void Informacion(string nombre, string apellido, string sexo, string email, string direccion, string ciudad, string requerimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Informacion", ReplyAction="http://tempuri.org/IService1/InformacionResponse")]
        System.Threading.Tasks.Task InformacionAsync(string nombre, string apellido, string sexo, string email, string direccion, string ciudad, string requerimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Registrado", ReplyAction="http://tempuri.org/IService1/RegistradoResponse")]
        bool Registrado(string nombre, string apellido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Registrado", ReplyAction="http://tempuri.org/IService1/RegistradoResponse")]
        System.Threading.Tasks.Task<bool> RegistradoAsync(string nombre, string apellido);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Lab6.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Lab6.ServiceReference1.IService1>, Lab6.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] getCiudades() {
            return base.Channel.getCiudades();
        }
        
        public System.Threading.Tasks.Task<string[]> getCiudadesAsync() {
            return base.Channel.getCiudadesAsync();
        }
        
        public void Informacion(string nombre, string apellido, string sexo, string email, string direccion, string ciudad, string requerimiento) {
            base.Channel.Informacion(nombre, apellido, sexo, email, direccion, ciudad, requerimiento);
        }
        
        public System.Threading.Tasks.Task InformacionAsync(string nombre, string apellido, string sexo, string email, string direccion, string ciudad, string requerimiento) {
            return base.Channel.InformacionAsync(nombre, apellido, sexo, email, direccion, ciudad, requerimiento);
        }
        
        public bool Registrado(string nombre, string apellido) {
            return base.Channel.Registrado(nombre, apellido);
        }
        
        public System.Threading.Tasks.Task<bool> RegistradoAsync(string nombre, string apellido) {
            return base.Channel.RegistradoAsync(nombre, apellido);
        }
    }
}
